### ISSUE TITLE
View annotation levels of type ITEM together with dependend level type SEG/EVE

### ISSUE THREAD

**Issue by florianschiel** [IPS-LMU/EMU-webApp#104]
It would be a nice, useful feature to display ITEM annotations not only in the hierarchical view but also in the 'normal' view together with dependent SEGMENT/EVENT level annotations.
Such levels should be 'visibly dependend' (e.g. by painting them in a shaded color) to signal the user  that this annotation level cannot be changed but inherits its time information from another level.
If an ITEM level is selected for display that has no links to a SEGMENT/EVENT level, the frame could contain a message indicating that this makes no sense. 
Such a view would help labellers to identify locations in long phonetic sequences by looking through e.g. a word level annotation.
This feature was not possible in the legacy Emu system.

**Comment by samgregory** [comment]
Hi @MJochim - this functionality now exists in EMUwebApp through the **Show hierarchy path canvas** setting. So we can close this issue. Unfortunately I have to open an new issue because I just discover that the hierarchy path canvas doesn't work in embedded mode on Rstudio.

**Comment by MJochim** [comment]
True, thanks for the note.
