### ISSUE TITLE
Firefox cursor problem in textfield in spec. setting

### ISSUE THREAD

**Issue by raphywink** [IPS-LMU/EMU-webApp#109]
There seems to be a cursor problem in the textfields of the spec. settings modal under Firefox: It does not react to any cursor arrow movements. The the JavaScript console outputs the following error:

`KeyboardEvent.key-Wert "Right" sollte nicht mehr verwendet werden und wird auf "ArrowRight" unbenannt. Für weitere Hilfe siehe https://developer.mozilla.org/en-US/docs/Web/API/KeyboardEvent.key`

**Comment by georgraess** [comment]
which version are you using ? 
i have firefox 38.0.5 and there is no such bug...
maybe you could post under which ff version this bug occurs ?

**Comment by georgraess** [comment]
ff version problem
