### ISSUE TITLE
Multi select & move of EVENTs

### ISSUE THREAD

**Issue by raphywink** [IPS-LMU/EMU-webApp#113]
It should be possible to select single multiple EVENTs (just like SEGMENTs) and move them by pushing down and holding the alt key.

**Comment by georgraess** [comment]
on the SEGMENTs we check if it is allowed to select multiple (bevore moving them) by comparing start&end times of the corresponding segments...
how should we check that on events ? 

i.e. in this situation:
![image](https://cloud.githubusercontent.com/assets/4677716/8475887/f3f8ff6e-20bb-11e5-87dc-5a193a50b8f2.png)

should it be allowed to multiple select the left H* and L ?

**Comment by raphywink** [comment]
I think it should only be possible to select "direct neighbors" as groups of "preselected EVENTs". If L- is preselected right-clicking the left H*@18631 or the right H*@38254 should result in two preselected EVENTs. If L- is preselected right-clicking on H*@8381 should result in  H*@8381 being preselected and nothing else.

**Comment by georgraess** [comment]
there is still a small bug that not all events get selected... gonna fix that tomorrow morning
