### ISSUE TITLE
constants and multiple language support

### ISSUE THREAD

**Issue by georgraess** [IPS-LMU/EMU-webApp#117]
just an idea:
we could use angular's constant to unify all the constants we use....
we could also use that feature to implement multiple language support 
(is this desired ? or not ?) like in a first draft here:

https://github.com/IPS-LMU/EMU-webApp/commit/d69fa79aa618a73e061941307a86db62c4d99191

?

**Comment by raphywink** [comment]
Not a huge fan of this! If we in future do want to support multiple languages (don't think that will happen any time soon if at all!!!! Maybe as part of the Angular 2.0 refactor that we get to do next year :-)???) we should try to externalize the language dependent items out of our code so we could get other people to translate them for us already forcing them to use the correct format (probably JSON files containing all the language specific things (every modal button text and so on...)).

**Comment by raphywink** [comment]
Could you maybe revert (or just change back) the code you added to the master branch?
