### ISSUE TITLE
angular.copy seems to be a performance bottleneck

### ISSUE THREAD

**Issue by raphywink** [IPS-LMU/EMU-webApp#125]
I just profiled a boundary move on the msajc003.TextGrid (= lots of Segment/Event levels). And it seems that something is calling angular.copy a lot! This seems to take the largest amount of time in the $digest cycle. Does anyone know what could be causing this? I had a brief look and couldn't find the culprit.
![screen shot 2015-08-19 at 13 29 51](https://cloud.githubusercontent.com/assets/435436/9355244/9a2b9d34-4677-11e5-9aba-01f8ff1245ad.png)

**Comment by georgraess** [comment]
performance bottleneck removed =)
still need to adjust test and so on....

**Comment by raphywink** [comment]
Just remembered: Don't forget to also change the getTextImageTwoLines() function to paint directly onto the context as well. Maybe rename both functions to something like:
```js
drawUndistortedText()
drawUndistortedTextTwoLines()
```
