### ISSUE TITLE
Left Menu contains session items out of reach ...

### ISSUE THREAD

**Issue by florianschiel** [IPS-LMU/EMU-webApp#137]
... when session list is long.
The scroll bar is at its end, but there are still 3 more sessions in the DB that are not shown in the left menu (and are therefore not loadable).
Tested with Chrome Version 44.0.2403.130 (64-bit) and on emu DB
/vdata/BAS/KielCorpusRead/KielCorpusRead.emuR/

**Comment by georgraess** [comment]
have to redo online mode/with subcategories

**Comment by raphywink** [comment]
Closing this issue as it does not seem to be an issue any more (just tested it with this emuDB: /vdata/BAS/KielCorpusRead/KielCorpusRead_emuDB/)
