### ISSUE TITLE
Zoom in hierarchical view only in time dimension

### ISSUE THREAD

**Issue by florianschiel** [IPS-LMU/EMU-webApp#138]
When using the hierarchical view on a large recording with a complex hierarchy, e.g.
emu DB /vdata/BAS/KielCorpusRead/KielCorpusRead.emuR/, bundle g071a000, the labels 
of the last layers are starting to overlap which is ok.
But when zooming in to make them readable, the zoom moves away all the upper layers, because the distance between levels is zoomed as well (= zooming in two spatial dimensions). The user ends up with a readable level but has to scroll around then to read the corresponding upper levels which is quite cumbersome.

Could the zoom function be restricted to the dimension that represents the time (default vertical, but when you flip, then it would be horizontal)?

**Comment by raphywink** [comment]
Just released a new version containing your fixes. I noticed however that one can't click and drag the area along the vertical axis either any more. Do you think it would be possible to implement this?

**Comment by MJochim** [comment]
Do you mean the vertical axis when in flipped mode? ie, the non-time-axis? It should currently be possible to click and drag along the time axis but not along the other axis. Although this was only a by-product of my coding efforts, @florianschiel and I agreed that this behavior is actually useful. There should be no need to move the other axis and this way you cannot easily "get lost".

**Comment by MJochim** [comment]
just noting what @raphywink and i just discussed:

The current behaviour is fine for a limited number of levels (e.g 7 in ae database). For the future, however, we do not know how many levels will be employed by our users. We are therefore bound to run into the problem of too many levels stuffed into too little screen. The webapp should be able to handle this.

As for the "getting lost" argument - this is actually a completely different issue. The hierarchy view should know where the tree ends and prevent the user from scrolling to some far away place.
