### ISSUE TITLE
mobile friendliness / shortcuts

### ISSUE THREAD

**Issue by georgraess** [IPS-LMU/EMU-webApp#139]
besides redesigning some of the css for mobile devices, how do we handle keyboard shortcuts on mobile devices ? (i.e. iphone/android/tablet)

a) should we reserve some space at the bottom for an onscreen keyboard ? 
   (simple solution not much to do but not much space on screen)
   and leave the rest of the shortcut functions as is

b) or should we 
     1) detect if it is a mobile device (easy)
     2) if it is a mobile device adopt/expand the functionality of handleKeyStrokes 
         to maybe handleKeyAndSwipeStrokes (a lot to do)
     3) and assign a swipe or other gestures to each function or a partially to some functions
         (i.e. two finger zoom -> zoom in / two finger zoom -> zoom out / double tap -> rename / etc.)

problems:
- we have to think of a good gesture -> functionality mapping
- i think there are some predefined gestures, if we need more we have to code them

**Comment by raphywink** [comment]
I definitely think that B ist the way to go. We should maybe also consider adding a mobile "choose tool" menu in the form of something like this: https://material.angularjs.org/latest/#/demo/material.components.bottomSheet. This could then show things like "preselect boundary tool"/"move boundary tool"/"correct contours tool"/...

**Comment by raphywink** [comment]
currently not relevant! Might reopen in future
