### ISSUE TITLE
Reverse Engineering

### ISSUE THREAD

**Issue by aloknath1** [IPS-LMU/EMU-webApp#141]
I am doing the reverse engineering in it. Below are my requirements:

Waveform Display / Labeler   :   Provide PRAAT like capability.  Mark boundaries using mouse.  Add new boundaries with hot keys.  Be able to see the frequency content of the audio.  Adjust zoom
Input trans file formats            :   .trans / json
Output trans file formats         :  .trans / json
Transcription Hints                  :    Display either the current transcription or a pre-transcribed file
Support 1 or 2 channels          :  The transcriptionist should be able to switch between 1 and 2 channel audio when applicable

I want to know how feasible is it to do. I have to dragndrop the wav files. 
I had debugged that the waveforms of audio files are drawing on parsing the JSON blob data, but I don't want that way.

**Comment by raphywink** [comment]
"Waveform Display / Labeler : Provide PRAAT like capability. Mark boundaries using mouse. Add new boundaries with hot keys. Be able to see the frequency content of the audio. Adjust zoom"

The EMU-webApp is already able to do this. The "General usage" section of the manual describes how this can be done (click on the Icon on the top right hand side of the EMU-webApp: http://ips-lmu.github.io/EMU-webApp/).

"Input trans file formats : .trans / json"
"Output trans file formats : .trans / json"

We currently support TextGrid files and our annotJSON file format (Schema URL: https://github.com/IPS-LMU/EMU-webApp/blob/master/dist/schemaFiles/annotationFileSchema.json) that can be drag & dropped onto the webApp (as files pairs with the same base name: bla.wav & bla_annot.json). I have never heard of the ".trans" file format? Could you provide further information?

"Transcription Hints : Display either the current transcription or a pre-transcribed file"

Sorry I don't quite understand what you mean by this. The EMU-webApp (as every other labeler that I know) always displays the contents of the current annotation file. Doing things like restricting the labelsets to ensure a more consistent annoations  are possible with the webApp using a server that supports the EMU-webApp websocket protocol 

"Support 1 or 2 channels : The transcriptionist should be able to switch between 1 and 2 channel audio when applicable" 

Our current focus is to support mono wav files. In future we could definitely think about adding multi channel wav files (adapting the parser and rendering functions to do should be doable) support but that is not our main focus at the moment.

"I had debugged that the waveforms of audio files are drawing on parsing the JSON blob data, but I don't want that way."

https://github.com/IPS-LMU/EMU-webApp/blob/master/app/scripts/services/DragnDropService.js#L132 is drag & drop function call to our wav file parser. This converts the wav file into an internal javascript typed array form that we then use to throughout the app.

Hope this helps...

**Comment by raphywink** [comment]
closing issue as it seems to be inactive
