### ISSUE TITLE
play part of a hierarchy may not work when the links have just been added

### ISSUE THREAD

**Issue by MJochim** [IPS-LMU/EMU-webApp#147]
**Steps to reproduce**
Add a new item (e.g. word level) and link it to several items on a time level. If you create the link in the right order (i.e. from first to last on the time axis), you can also play back the parent item. If you create them in a different order, playback will be from the first link that you have created to the last link you have created (i.e. their position on the time axis is not considered). Loading another bundle and then reloading the first one makes playback work.

**Comment by MJochim** [comment]
Correction: Loading another bundle and then reloading the first one only **sometimes** makes playback work.

**Comment by raphywink** [comment]
Just FYI: The Links array is to be considered a set not an ordered array! So the order should never matter...
