### ISSUE TITLE
moving a boundary breaks undo stack under some conditions

### ISSUE THREAD

**Issue by MJochim** [IPS-LMU/EMU-webApp#148]
When the keyboard focus is not on the webapp, but rather e.g. on the browser's address bar, I can still move boundaries by holding down shift and moving the mouse. However, the bundle is not marked red/changed and the move cannot be undone. Changing bundle does not warn the user and the move is lost.

When I move a boundary like above (with keyboard focus away from the webapp) and then get keyboard focus back onto the webapp and move another boundary, the behaviour turns rather more bizarre. The bundle is immediately marked red/changed and pressing "undo" (or then "redo") reverts both boundaries at the same time.

Reverting both boundaries at the same time does not seem to take place when the first boundary I move is the last in the utterance and the second is the one before it.

**Comment by MJochim** [comment]
Note: I first spotted this problem using the Neo keyboard layout (under Linux). When I use Neo, boundary moves are never added to the undo stack, no matter where the keyboard focus is. I can use the undo stack for other things, but the boundary moves are just ignored. Seems pretty dangerous to me.

**Comment by raphywink** [comment]
This is super weird!!! I can also reproduce the "keyboard focus in address bar" problem on my Mac. Could it have something to do with the "shift-keyup" event (that we catch here: https://github.com/IPS-LMU/EMU-webApp/blob/master/app/scripts/controllers/main.js#L50) not being thrown by the browser if the focus is not on the page?
