### ISSUE TITLE
inconsistency in emuwebappConfigSchema.json 

### ISSUE THREAD

**Issue by georgraess** [IPS-LMU/EMU-webApp#152]
there are some inconsistencies inside emuwebappConfigSchema.json 
(at least imho)..

for example:
in L178 - L187 regarding spectrogramSettings.properties : the structure is always like:

"object": {
    "type": "whatever"
}

But in L190 - L192 regarding the window object the "type" is missing.... !?
i cannot set the right input type (text, drop down etc) at the editDBConfig formular for an object if i do not know the type of the object from the schema.... 

there are also some other inconsistencies in emuwebappConfigSchema.json which i would like to correct
may i change this / correct this ?
or do we get into trouble then =) ?

**Comment by raphywink** [comment]
That schema file is to the json schema spec. version 4. So that is just how you specify enums in json schema...
