### ISSUE TITLE
labels are a tiny bit off center

### ISSUE THREAD

**Issue by raphywink** [IPS-LMU/EMU-webApp#153]
As can be seen here:

<img width="431" alt="screen shot 2015-10-27 at 10 31 48" src="https://cloud.githubusercontent.com/assets/435436/10754121/ecf03288-7c95-11e5-9a1a-e12f38ae2159.png">

The '@' symbol is a tiny bit of center in vertical as well as horizontal position. Just a tiny esthetic flaw but we should probably fix that in the long run...

**Comment by georgraess** [comment]
strange.... which browser and which version ? in chrome v46 it is now centered

![image](https://cloud.githubusercontent.com/assets/4677716/10843373/01578266-7ef9-11e5-8535-b9685aa642d1.png)

**Comment by raphywink** [comment]
Chrome 46.0.2490.80

![screen shot 2015-10-30 at 11 28 42](https://cloud.githubusercontent.com/assets/435436/10843459/7303f05c-7ef9-11e5-903d-0f04f82ee6e3.png)

The labels are displayed a tiny bit too far to the right and a tiny bit too far up (to close to the dark grey line). Max off by 1-2 pixels though... so nothing big

**Comment by georgraess** [comment]
in the master branch ?
or the fixed version in the config branch (added 2px to the right and 2px to the top)

https://github.com/IPS-LMU/EMU-webApp/commit/dd626eacb8d0aa20c7434864bef2c7aa09f6cbf2

**Comment by raphywink** [comment]
only checked on master branch. If you say it is now fixed then just tell me as soon as it is in the master branch then I'll double check it on my machine...
