### ISSUE TITLE
space fires two keypress events in hierarchy modal

### ISSUE THREAD

**Issue by MJochim** [IPS-LMU/EMU-webApp#156]
very strange ... space seems to be the only key to fire two keypress events. and this only happens when the hierarchy modal is active, or, more precisely, when handleKeystrokes.js has called toggleHierarchy().

This used to prevent playback via pressing space in hierarchy modal, because it would start playback and then immediately pause it. This seems to be no longer the case since the audio framework was changed in e39a897. But still the event is fired twice.

**Comment by georgraess** [comment]
maybe there is a problem in handleKeystrokes.js with multiple keyMappings inside default_emuwebappConfig.json ...

Line 24 : "hierarchyPlayback":  32
Line 30 : "playAllInView" : 32

handleKeystrokes is not intended to bind multiple functions to a single keystroke....

**Comment by raphywink** [comment]
interesting! @MJochim could you have a look? Maybe just temporarily change the keycode to see if it still fires two events?

**Comment by MJochim** [comment]
yep, i'll try it later today

Am 30.10.2015 um 14:05 schrieb Raphael Winkelmann:

**Comment by MJochim** [comment]
changing the shortcut for hierarchyPlayback doesn't help.

**Comment by MJochim** [comment]
I've tracked down the problem at least a little farther.

We have three primary event handlers in handlekeystrokes.js for keyup, keydown and keypress, respectively (on lines 9, 18, and 29).

* For keys like 'q', 'w', 'e' etc., all three of them are called. But only the keypress event handler will then call scope.applyKeyCode(). 
* For keys like space, escape, and tab, the keypress event handler is not triggered by the browser. keyup and keydown are triggered by the browser, and keydown calls scope.applyKeyCode().
* When the hierarchy modal is opened (ie, I guess, when d3js lib becomes active), the browser behaviour changes.
** For tab and escape, the behaviour remains the same.
** For space, the keypress event handler is now also triggered. In turn, both the keypress and the keydown event handler call scope.applyKeyCode(). That's our problem.

I do not yet know why the browser behaviour changes. I think it's due to d3js but it might be something completely different. Even if it were d3js, I do not see why it would do that.

** Possible solution **

In the keypress event handler (handlekeystrokes.js:29), we might check the key code and refuse to applyKeyCode() in case it's 32. It would do the trick.

Of course it would still be better to find out why d3js (or whatever) changes browser behaviour and then patch that. What do you think?

**Comment by MJochim** [comment]
... "i am with my latin at the end" :( ...

While trying to find out at what point the browser behavior is modified, I commented out the hierarchy view, the hierarchy directive, the hierarchy controller. I even commented out the modal.open()... no success. I only know that the browser behaviour is modified when viewState.hierarchyState.hierarchyShown is set to true. But I am absolutely clueless about where this variable is evaluated (after I have the commented out all the places I know). I even grepped over the whole app directory to find all places where this variable or its getter method are referenced, but to no avail.

**Comment by raphywink** [comment]
@georgraess any ideas? Unfortunately I won't have much time to look into this in the next few days...
