### ISSUE TITLE
Changing selection on signalcanvas

### ISSUE THREAD

**Issue by MJochim** [IPS-LMU/EMU-webApp#162]
If I make a selection on a signal canvas and then decide that I want to change it just a bit (e.g. if I have not managed to select a complete vowel), I am forced to re-create the whole selection.

It would be great to expand or reduce the current selection by holding down shift and clicking the desired position of the start/end of the selection. This is the way it works in most any software (selecting text in a text field, selecting files in a file browser, selecting sound in Praat, ...).

On the level canvases, we have something quite similar in place: right-clicking adjacent items does the trick (which I didn't know was possible before I read it in the general usage instructions five minutes ago ;-)). I would also love to see this working with shift but I can see that shift already does a different job there. To be consistent, it might then be better to use the right-click on the signal canvases as well.

**Comment by raphywink** [comment]
I think we should go with the shift+click alternative (as just discussed...)
