### ISSUE TITLE
Opening help modal while loading leaves webapp in undefined state

### ISSUE THREAD

**Issue by MJochim** [IPS-LMU/EMU-webApp#163]
This is a minor issue. You have to be really quick at step 2 to cause a problem.

**Steps to reproduce**

1. Open a database (Connect to server or demo db)
1. While the webapp is loading the db, open help modal by clicking the Emu
1. Press escape to close the help modal
1. The modal does not disappear

Closing the modal via X button works. However, it leaves the webapp in "modal state" (i.e., all buttons at the top are greyed out). Pressing escape then puts the webapp into right state.

Mind you, you have to be really quick at step 2. It works best if you're developing and have set up auto-connect (you can then position the mouse over the Emu and do step 2 by hitting F5).

**Comment by raphywink** [comment]
https://github.com/IPS-LMU/EMU-webApp/commit/88cb809670a3d5e4fb2d45a9b67a39c5d520c382 should fix this! Can you check it out and close the issue if it did?

**Comment by raphywink** [comment]
Also we should put more emphasis on our "state machine". This could also be lacking in other parts of the webApp.

**Comment by MJochim** [comment]
yep, your fix seems to have worked. Maybe we should talk about the state machine thing during our next meeting.
