### ISSUE TITLE
Hierarchy links not showing up in hierarchy view Version: 0.0.31

### ISSUE THREAD

**Issue by hywel** [IPS-LMU/EMU-webApp#164]
Links that were working in version 0.028 seem to have disappeared in the hierarchy view within version 0.0.31 on Chrome (46.0.2490.86 (64-bit) on OS X).

**Comment by raphywink** [comment]
Could you maybe put together a mini emuDB for us so we have an example to go by (DBconfigJSON + a single _bndl)? I can't see any problems with our normal test databases.

**Comment by florianschiel** [comment]
Raphael: könnte das der (schon gefixte) Fehler sein, den wir vor ein 
paar Wochen hatten wegen korrupter file caches?
Vielleicht muss Hywel nur den file cache löschen und neu laden?

**Comment by raphywink** [comment]
@florianschiel: I don't think that it is due to a broken cache. The only thing that was "broken" in the database cache was that redundant links where not kept up-to-date. These redundant links are only used in hierarchical queries and requeries. But @hywel you can maybe try it out anyway: Just delete the _emuDBcache.sqlite file in the top level of your emuDB and then reload the database.

**Comment by hywel** [comment]
Thanks @raphywink and @florianschiel - I have tried rebuilding the database cache but the problem remains. Other databases seem OK however. The particular database that has problems has times defined for each of the tiers (7 tiers). I have converted this from legacy emu  (in order to construct the linked hierarchies). I have attached the DBconfigJSON and I can try to create a mini database if that will help?

[MAWNG_Tape_179_DBconfig.json.txt](https://github.com/IPS-LMU/EMU-webApp/files/37453/MAWNG_Tape_179_DBconfig.json.txt)

**Comment by MJochim** [comment]
@hywel: That will indeed help very much. Could you then also point out which links do not show up?

**Comment by MJochim** [comment]
@hywel do they appear in yellow when you hover the mouse cursor over them? We're having the problem that all levels of type SEGMENT or EVENT (ie, levels with time information) are drawn with a dark grey background color that is the same as the color of the links themselves. That is why they're "invisible". We'll release a fix for that very soon.

**Comment by hywel** [comment]
@MJochim: Thanks for investigating - I see now that the links are just camouflaged.
