### ISSUE TITLE
Unable to create regions on clean canvas using Marker

### ISSUE THREAD

**Issue by aloknath1** [IPS-LMU/EMU-webApp#169]
Scenario 1:
a. Uploading the wav file using drag & drop option, then "add segment".
b. Starting clicking on canvas to insert the marker, on "enter" there is no marker action
Issue: Interval is not created using marker

Scenario 2:
a. Uploading the wav file using drag & drop option, then "add segment".
b. Using drag & selection for creating intervals doesn't get enabled/created on "enter" key shortcut.

Both the scenario are evident on using the uploaded wave file. After few random attempts we are able to to drag and create region, then it allows to use either drag or marker to create intervals. But cannot start creating the regions/interval using markers.

**Comment by raphywink** [comment]
Just tested it using this audio file: https://github.com/IPS-LMU/EMU-webApp/blob/master/app/testData/newFormat/ae/0000_ses/msajc003_bndl/msajc003.wav and it does seem to work on my end. Here is what I did:

- drag & drop audio file onto drop area of webApp
- click "add level (SEG.)"
- click onto new level to preselect it (turns a darker shade of grey). Alternatively you can also use the up and down cursor keys to select the current preselected level
- mark a segment in the OSCI or SPEC canvas
- hit enter

We should however probably automatically preselect the level that has just been added. @georgraess could you have a look at implementing this?

**Comment by aloknath1** [comment]
It is creating a region on marker but at first creating the region after drag not on inserting the marker at first before region drag

**Comment by raphywink** [comment]
Sorry but you are going to have to elaborate a bit. I do not really understand what you are referring to in  your last comment.

**Comment by aloknath1** [comment]
I understood the way to create boundaries using mouse drag and then pressing enter/return key, but if i want to start with just using single event marker to create intervals. Using single event marker also works but after one interval is created using drag.
It so that i use "praat" desktop GUI where inserting single event marker creates left and right regions right from start of creating intervals.

Let me know how to create the intervals using single event marker from very first?

**Comment by raphywink** [comment]
Ok now I know what you mean. You are right, that is not possible using the EMU-webApp. You have to first create a segment then you can add single boundaries to the left/right of that segment (or between) to create new segments but you can't add a single boundary to an empty level that then creates two segments which together are the length of the entire audio file. To be honest I don't quite know what to think of that behaviour and if it has any benefits for the annotator.

**Comment by raphywink** [comment]
This preselects the level (which is a good thing) but it does not fix the issue -> reopening issue
