### ISSUE TITLE
How to connect to database MongoDb in EMUwebApp

### ISSUE THREAD

**Issue by aloknath1** [IPS-LMU/EMU-webApp#170]

**Comment by raphywink** [comment]
You would have to implement a server that supports the EMU-webApp-websocket-protocol that is described here: https://github.com/IPS-LMU/EMU-webApp/blob/master/dist/manual/EMU-webAppWebsocketProtocol/EMU-webApp-websocket-protocol-0_0_2.md

**Comment by raphywink** [comment]
Closing this for now. If you are interested in the database format that we support in the emuR package (server implementations already exist for this format), a good  starting point is the emDB vignette of the emuR package: https://github.com/IPS-LMU/emuR/blob/master/vignettes/emuDB.Rmd
