### ISSUE TITLE
Support for two channel audio files

### ISSUE THREAD

**Issue by mnrao2001** [IPS-LMU/EMU-webApp#171]
Please let me know the feasibility of;
a) Using "wavParserWorkerClass.js" to support 2-Channel audio files.
b) Modifying the UI upper-panel the need is to display oscillogram for both the channels and to display spectrogram of channel 1 audio stream only. 

Is there any plan of providing multi-channel audio file support feature in the pipeline?

**Comment by raphywink** [comment]
Although theoretically possible we have opted (for the time being anyway) to stick with single channel uncompressed wav files only. Multi channel audio would extremely bloat the configuration of an emuDB (and require a bucketload of extra code) as it would mean we would have to think of things like:

- what to draw on the SPEC canvas (channel X / mix of channel X & Y & ... (volume relationship?) / switchable SPEC canvas / multiple SPEC canvases ??)
- what audio to play (channel X / mix of channel X & Y & ... (volume relationship?) / switchable audio option? / ...)
- what do we do with interleaved vs non-interleaves multi-channel audio? Treat them the same?
- how to we link the annotations to the channel? Think multi Mic recordings... 
- when extracting / computing derived signals such as F0 what channel should it default to?
- ...

In future we might try to takle these questions, but for now we are sticking with single channel audio as the CRAN release of emuR is currently the priority.

What do you want to do with your multi channel audio? Maybe there is a workaround we can help you with?

**Comment by mnrao2001** [comment]
It's so that we instruct our transcribers to listen the 2-Channel audio files and ask only to transcribe Channel 1 audio stream events. Channel 2 audio stream provides cues to the transcriber to decide upon that the some events source on Channel 1 is due the cross-talk/headset-speaker interference and not part of the primary microphone inputs, and those events are tagged accordingly. (Our headset is mounted with multiple microphones)

**Comment by raphywink** [comment]
Sorry for the late reply. I am afraid that aside from "merging" audio files into a single audio file we currently don't have a solution for you. In the long run I'll try to get multi channel audio to work but that could be a few months away.

**Comment by raphywink** [comment]
Multi-channel audio is now supported
