### ISSUE TITLE
How to load the file from a treeview?

### ISSUE THREAD

**Issue by aloknath1** [IPS-LMU/EMU-webApp#175]

**Comment by raphywink** [comment]
I don't quite know what you mean by treeview but I suspect you mean the hierarchical modal view. If so, then you can read up on our json file format that supports linking of annotational units (called items in the context of an emuDB) in the vignettes of our emuR R package. The uncompiled source versions of the two vignettes that are probably relevant to your problem can be found here:

- overview: https://github.com/IPS-LMU/emuR/blob/master/vignettes/emuR_intro.Rmd
- contains file format descr.: https://github.com/IPS-LMU/emuR/blob/master/vignettes/emuDB.Rmd
