### ISSUE TITLE
Fetching wavefile from URL 

### ISSUE THREAD

**Issue by aloknath1** [IPS-LMU/EMU-webApp#176]
I'm implementing file browser feature in EMU-webApp whereby the transcriber browses the hosted .wav & _annot.JSON file pairs unlike the Drag&Drop. Currently i'm able to browse and fetch the wavefile from remote server but unable to get the blob data from the wavefile, Below are the functions calls i'm invoking to parse the wavefile. But, on Step3 I'm getting an exception :"Error parsing wav file: [object Object]". If at all I can see the blob content in the console. 
Attached the screenshot.
Step1: var url1 = 'http://localhost:80/files/mFL0a_fl_fa_2.wav';
           $http({
                method: 'GET',
                url: url
            }).then(function(response){
				console.log(response.data);		
				blob_data = response.data;	
			});
Step2: var ab = Binarydatamaniphelper.base64ToArrayBuffer(blob_data);
Step3: Wavparserservice.parseWavArrBuf(ab).then(function (messWavParser) 

![wavefile-parser-error](https://cloud.githubusercontent.com/assets/6869264/12778376/6b4ffb3c-ca88-11e5-8594-2c129678d21a.JPG)

**Comment by raphywink** [comment]
If by "file browser feature" you mean hosting multiple files to the webApp we have already implemented this feature utilizing the websocket protocol. How we use this protocol is described in the EMU-WebSocket Protocol part of the manual: 

https://github.com/IPS-LMU/EMU-webApp/blob/master/app/manual/EMU-webAppWebsocketProtocol/EMU-webApp-websocket-protocol-0_0_2.md

And is implemented by this Node.js server:

https://github.com/IPS-LMU/IPS-EMUprot-nodeWSserver

and the `serve` function of the emuR package:

https://github.com/IPS-LMU/emuR

If by "file browser feature" you mean that you want to host links to the EMU-webApp that automatically opens hosted files from a different location (via GET call) you can simply do this by using the get parameters like in this example:

http://ips-lmu.github.io/EMU-webApp/?audioGetUrl=XXX&labelGetUrl=YYY&labelType=TEXTGRID

To the problem you are having in your code is related to the type of object you are passing in to the `Wavparserservice.parseWavArrBuf` function. You can see how we handle GET requests here: https://github.com/IPS-LMU/EMU-webApp/blob/master/app/scripts/controllers/main.js#L151

hope this helps...

**Comment by aloknath1** [comment]
What should be the labelType for a bundle in the below url: 

http://ips-lmu.github.io/EMU-webApp/?audioGetUrl=XXX&labelGetUrl=YYY&labelType=TEXTGRID

**Comment by raphywink** [comment]
Good question. Funnily enough I don't know if we currently support the `_annot.json` format in the get parameters (which is a bit embarrassing as it is our own format :-)). @georgraess do you know off by heart if  we have allow `annotJSON` as the label type? Just glancing at the code it doesn't seem like we do...

**Comment by georgraess** [comment]
yes we do allow annotJSON without a problem.
the corresponding url is

http://ips-lmu.github.io/EMU-webApp/?audioGetUrl=XXX&labelGetUrl=YYY&labelType=annotJSON

where you replace XXX with a wav url and YYY with an _annot.json file. (with type=annotJSON)

BUT !!!!

there is no 'Access-Control-Allow-Origin' header is present in the github hosting. (no CORS)
therefore you cannot load other urls than (http://ips-lmu.github.io/EMU-webApp/) from the hosted github page. and there is also no way to get github to enable CORS. and we have (at the moment) no wav and no _annot.json hosted below that url.

so right now (using http://ips-lmu.github.io/EMU-webApp/ as a start) is NOT able to load a foreign url, because of the Same-Origin-Policy (.... although the code is already implemented).

the only way to load foreign url data right now is to host the app yourself and allow CORS

here is some background information on CORS (in german) :

https://de.wikipedia.org/wiki/Cross-Origin_Resource_Sharing

and in english :

https://en.wikipedia.org/wiki/Cross-origin_resource_sharing

**Comment by MJochim** [comment]
@georgraess please correct me if I'm wrong but I'm pretty sure the header needs to be present on the server hosting the wav and json files, not on the server hosting the app. after all, that is how we enable the "emu preview" results in the MAUS web service.

**Comment by mohitraj1** [comment]
Is there any timeline by when the CORS implemented code can be expected to
be hosted on github?

**Comment by georgraess** [comment]
@MJochim yeah your right 
i meant that... sorry if it sounded misleading....
you have to enable it on the server hosting the wav and the annot
(but even that is not possible with github as far as i know)

you can use the github web to load foreign content but only from servers where

Access-Control-Allow-Origin: http://foo.com
Access-Control-Allow-Methods: PUT, DELETE

is set

**Comment by raphywink** [comment]
Ehm yes it does :-). That is what webMAUS does all the time: 

http://ips-lmu.github.io/EMU-webApp/?audioGetUrl=https:%2F%2Fwebapp.phonetik.uni-muenchen.de:443%2FBASWebServices%2Fdata%2F2016.02.04_15.50.02_D0B0A14106586C6078979FBBA6A1B0B9%2Fmsajc003.wav&labelGetUrl=https:%2F%2Fwebapp.phonetik.uni-muenchen.de:443%2FBASWebServices%2Fdata%2F2016.02.04_15.50.02_D0B0A14106586C6078979FBBA6A1B0B9%2Fmsajc003.TextGrid&labelType=TEXTGRID

Steps to reproduce (as links is only valid for about a day or so):

1.) get these files: http://www.phonetik.uni-muenchen.de/~raphael/testData/msajc003.wav
http://www.phonetik.uni-muenchen.de/~raphael/testData/msajc003.txt
2.) go here https://clarin.phonetik.uni-muenchen.de/BASWebServices/#/services/WebMAUSBasic
3.) upload signal file & txt file
4.) click run and then the Segmentation Preview button

**Comment by georgraess** [comment]
@raphywink 
yeah but it does not automagically work with every server (like in the localhost example from aloknath1)
you have to enable cors

**Comment by raphywink** [comment]
@georgraess yep! You have to enable CORS on the server hosting the files. In the example above `https://www.webapp.phonetik.uni-muenchen.de`. Note that this is only "unidirectional", meaning on the client a single call to the server hosting the files is made but the webapp has no means of writing back to the server (via put/post/... requests). It is only meant for people to visualize/preview data. For actual interaction with a emuDB (e.g. saving annotation changes) we implemented the EMU-websocket-protocol (see post above).

**Comment by georgraess** [comment]
@mohitraj1 
the cors enabled code is already hosted on github  !
BUT:  the target server where the data (wav and annot) is hosted has to enable cors

so if you host data on localhost and want to load it using http://ips-lmu.github.io/EMU-webApp
you have to enable cors locally
