### ISSUE TITLE
AutoSelect the segment level

### ISSUE THREAD

**Issue by aloknath1** [IPS-LMU/EMU-webApp#177]
I want to auto-select the segment level once the wavfile is loaded. Please suggest me where i have to make it changes?

**Comment by raphywink** [comment]
This is our setter to add an item to the selected list: https://github.com/IPS-LMU/EMU-webApp/blob/master/app/scripts/services/viewState.js#L873. The actual selected items are stored in the  `viewState.curClickItems` array.

What I have been thinking about for quite some time though is to maybe expand the bundle schema: https://github.com/IPS-LMU/EMU-webApp/blob/master/app/schemaFiles/bundleSchema.json to include fields to enable preset zoom and select features. Something like:

```JSON
viewStartSample: 100,
viewEndSample: 2000,
selectedItemId: 32
```

That would mean that you could write server side code to preselect certain ITEMs to facilitate faster labeling. If this is a feature request that would be interesting for you let me know in this issue and I'll open up a feature request issue.

**Comment by raphywink** [comment]
Sorry I might have misread your issue. Do you mean you wish to preselect the level? Would it maybe be helpful for you if we change the behaviour of the webApp to always preselect the first level per default? Because currently no level is selected by default...

**Comment by raphywink** [comment]
@georgraess my fix breaks 3 of the unit tests. Probably simple missing dep. injections... could you have a look?
