### ISSUE TITLE
Load the page into an iframe

### ISSUE THREAD

**Issue by aloknath1** [IPS-LMU/EMU-webApp#178]
Can I load the right hand side column(where the wave stream shows) into an iframe. Will it create any issues on page reload. how can i open the right hand side into an iframe. If I pass the src url to iframe (http://localhost:9000/?audioGetUrl=http://localhost:9000/wav/dc/mFL0a/mFL0a_fl_fa_2.wav&labelGetUrl=http://localhost:9000/wav/dc/mFL0a/mFL0a_fl_fa_2.TextGrid&labelType=TEXTGRID)

How much it will affect later workflow?

![wav_load](https://cloud.githubusercontent.com/assets/6869264/12939906/5d2d15e6-cfea-11e5-8bf6-ffb0c9d8ee8f.JPG)

**Comment by raphywink** [comment]
Placing the webApp into an iframe should work but is not recommended (and not tested either). One of the major problems with using iframes will be that the webApp won't be able to grab the bindings of the keystrokes hence actually labelling will be nearly impossible.

The webApp can however be included into a webpage using it's embedded mode (should work but not well tested yet). See here (the commented out section) for an example:  https://github.com/IPS-LMU/EMU-webApp/blob/master/app/index.html#L75

Once / If we make the switch to angular 2.0 we should be able to wrap the entire webApp into a web componted which should make it a lot easier to embed it into other web pages. But that is still a long way away and will be a massive rewrite which I am really looking forward to... ;-).

You seem to be trying a lot of different approaches using the EMU-webApp. What exactly do you want to achieve / how do you plan on using it? If you give me a detailed description of what you wish to do I might be able to provide you with a solution. If you don't want your plans to be public in an issue on GitHub you can also contact me via email. All my details are here: http://www.en.phonetik.uni-muenchen.de/people/phd_students/winkelmann_raphael/index.html
