### ISSUE TITLE
How to get all the buttons on the top

### ISSUE THREAD

**Issue by aloknath1** [IPS-LMU/EMU-webApp#179]
I want to show all the buttons on the top. I am getting only two buttons(download TEXTGRID and Spec settings) once i upload the wav file along with textgrid file. I have setting the values into below variables:
 audioGetUrl = 'http://localhost:9000/wav/mni/mHP0c/mHP0c_hp_fa_0.wav'
 labelGetUrl = 'http://localhost:9000/wav/mni/mHP0c/mHP0c_hp_fa_0.TextGrid'

Please find the attached snapshot:
![after_loading](https://cloud.githubusercontent.com/assets/6869264/12972963/6e0f3be2-d0cf-11e5-9d09-c757114b1a07.JPG)

**Comment by raphywink** [comment]
What buttons are displayed are set in the DBconfig.json of the emuDB. On loading files via drag & drop this file is used: https://github.com/IPS-LMU/EMU-webApp/blob/master/app/configFiles/standalone_emuwebappConfig.json
