### ISSUE TITLE
Change the preview of the wav

### ISSUE THREAD

**Issue by aloknath1** [IPS-LMU/EMU-webApp#180]
I want to change the preview content after loading the wavfile. The preview is not showing once the wavfile is uploaded. and if I upload another wavfile, it shows the preview content of previous wavfile.

Please find the attached screenshot

![change_preview](https://cloud.githubusercontent.com/assets/6869264/13047018/3e5f97da-d402-11e5-8778-9ae9c95cd35b.JPG)

**Comment by raphywink** [comment]
See the watches in the corresponding directive: https://github.com/IPS-LMU/EMU-webApp/blob/master/app/scripts/directives/preview.js
