### ISSUE TITLE
web worker variable overwritten

### ISSUE THREAD

**Issue by georgraess** [IPS-LMU/EMU-webApp#181]
while rewriting the ssff parser i stumbled across this:

https://github.com/IPS-LMU/EMU-webApp/blob/master/app/scripts/workers/ssffParserWorkerClass.js#L484

why do we make a json string out of an object in order to make the json string into an object ?

if i rewrite it to:     resArr.push(ssffJso); 
it overwrites all the values in resArr with the last one ?

it seems like there is something strange going on inside the ssffparser o.O

**Comment by MJochim** [comment]
I haven't looked closely at the function, but generally it can be a (somewhat flawed) way to copy an object rather than store a reference.

**Comment by raphywink** [comment]
Lines of code marked `// YUCK... don't know if SIC but YUCK!!!` usually mean that I wasn't 2 happy with what I was doing ;-). Off the top of my head I can't remember why I did it but it could have been the reference avoiding thing that @MJochim just mentioned.
