### ISSUE TITLE
Unit Testing

### ISSUE THREAD

**Issue by aloknath1** [IPS-LMU/EMU-webApp#182]
I want to know how to do unit testing using jasmine and karma. If anyone can guide me, how to do as I am new of it. So that I can start.

**Comment by MJochim** [comment]
are you new to unit testing in general, or to the specifics of angular/javascript unit testing?

**Comment by aloknath1** [comment]
Yes, I am new to unit testing in general. Using **grunt test** command, no task is executing. After running the 'grunt-test' command. I am getting this 
![grunt-test](https://cloud.githubusercontent.com/assets/6869264/13809377/94253bf2-eb90-11e5-983c-3824c664f48a.JPG)

**Comment by raphywink** [comment]
Have you installed all the dependancies with `npm install` and `bower install`? I have never tried running our unit test on windows so unfortunately I can not be of any help on that specific platform (we might even have some unix specific paths in some of our config files...). Have you tried using something like the mingw console (or simply the git bash console which is built on top of mingw)? That should also accept unix paths
