### ISSUE TITLE
Player progress bar not playing till the end and keeps being visible when playing selection 

### ISSUE THREAD

**Issue by thomaskisler** [IPS-LMU/EMU-webApp#190]
When zooming in a few times into a freshly loaded signal/annotation pair, selecting a word and hitting "c", the player progress bar does not go all the way to the right and dissappears (presumably that is the desired behavior), but stops consistently before the end of the boundary and keeps being visible.

After moving the mouse the "dark grey" progress bar dissapears. Example files could be provided.

**Comment by raphywink** [comment]
Yep! We are obviously missing the final repaint to clear the "dark grey" bar and it is just stuck at the last event "play head is currently at sample X". Should be an easy fix... probably just not reacting to a final "finished playing" event. Thanks for pointing it out!
