### ISSUE TITLE
renaming to bower convention

### ISSUE THREAD

**Issue by georgbramm** [IPS-LMU/EMU-webApp#191]
a new version of bower (forces) warns us that the app name convention at bower is now all lowercase

i renamed the EMU-webApp to: "emu-webapp" (see bower.json -> "name") inside the bower universe

**Comment by raphywink** [comment]
Yep that is fine! I noticed the bower warning as well! We should maybe also look at the convention for angular modules. We currently have a camel case notation for our module: emuwebApp. Maybe we should just change everything to emuwebapp. What do you think?

**Comment by raphywink** [comment]
not using bower any more...
