### ISSUE TITLE
Bug Email 

### ISSUE THREAD

**Issue by georgraess** [IPS-LMU/EMU-webApp#192]
we need an email address, used to collect bugs by email
currently it is set to emu@phonetik.uni-muenchen.de
we either have to create that email or use another one
the email address can be change inside 

package.json ( -> bugs -> email)

**Comment by raphywink** [comment]
emudevs@phonetik.uni-muenchen.de would be the correct email address.

**Comment by MJochim** [comment]
isn't it emugroup? or is that a larger audience? i've never noticed
emudevs being used.


Am 23.05.2016 um 11:00 schrieb Raphael Winkelmann:

**Comment by raphywink** [comment]
emuDevs currently only has me and Klaus in it but that could be expanded to include others of course. EmuGroup is just an internal address to include everyone who is loosely or less loosely involved in the EMU-SDMS but that would not be a better address for bugs.
