### ISSUE TITLE
Grunt Version 0.4.5 -> 1.0.1

### ISSUE THREAD

**Issue by georgraess** [IPS-LMU/EMU-webApp#193]
There is a problem with the newest Grunt version (1.0.1)

A LOT of plugins we use depend on grunt 0.4.5 
until either those plugins are updated to use 1.0.1 or we do get rid off them we have to stick to grunt@0.4.5

i up/downgraded to 0.4.5 in the branch angular-update

(also the changelog of grunt urges people tp upgrade:

 if you have a Grunt plugin that includes `grunt` in the `peerDependencies`,
      we recommend tagging with `"grunt": "">= 0.4.0"` and publishing a new version on npm.

see here : https://github.com/gruntjs/grunt/blob/master/CHANGELOG )

**Comment by raphywink** [comment]
If we have no deps. to grunt > 1.0.0 packages I do not see why we have to upgrade. So just keep it at 0.4.5
