### ISSUE TITLE
first segment cannot be played back or shortcut-navigated to

### ISSUE THREAD

**Issue by MJochim** [IPS-LMU/EMU-webApp#195]
I have a SEGMENT level with a number of items in it.

* When I select the first one, I cannot `play selected` - nothing happens.
* When I select the second one, I cannot use the arrow left to navigate to the first one - nothing happens.
* When I select the last one and use the arrow right to navigate past the signal, the dev tools show this: `TypeError: Cannot read property 'id' of undefined`.

It seems that a range check is broken - probabley uses 1..Array.length instead of 0..(Array.length-1).

I do not think this is input specific, but for the record I am including an [example bundle](https://github.com/IPS-LMU/EMU-webApp/files/287726/0014_prompt1_bndl.zip).

**Comment by raphywink** [comment]
Working on this now: Seems like it is not the players fault! Clicking on the first segment sets viewState.curViewPort.selectS to undefined -> player doesn't know where to start!
