### ISSUE TITLE
Ghost peaks in wave form

### ISSUE THREAD

**Issue by MJochim** [IPS-LMU/EMU-webApp#201]
I noticed that when I do not zoom into my wave file, the wave form may show "ghost peaks", i.e. amplitude peaks that appear much larger than they should. When I zoom into the file, those peaks vanish.

I have attached a wave file where this occurs (on my machine) and two screenshots at two different zoom levels. I do not know whether this happens rarely or often. Looking at the same file with Praat, there are no such ghost peaks.

[ghost_peaks.zip](https://github.com/IPS-LMU/EMU-webApp/files/541249/ghost_peaks.zip)

**Comment by raphywink** [comment]
I don't really think that this is a bug but how it is supposed to look when you calculate the average value for a specific window of samples. Here:

https://github.com/IPS-LMU/EMU-webApp/blob/master/app/scripts/services/drawhelperservice.js#L102

and here:

https://github.com/IPS-LMU/EMU-webApp/blob/master/app/scripts/services/drawhelperservice.js#L104

I calculate the average value for the current window and if that window has a lot of energy it will result in a spike. Imagine these three windows:

![zoom](https://cloud.githubusercontent.com/assets/435436/19555649/06b68a8a-96be-11e6-8909-7361aaf89a9b.png)

Window 1: very low average
Window 3: pretty low average
but
Window 2: very high average

if these values are then drawn onto a canvas by connecting the three pixels to draw the envelope of the OSCI it will result in a "ghost" peak. (Note that this is only true for the multiple samples per pixel case)

**Comment by MJochim** [comment]
This is definitely a low-priority issue.

I can see now that there is a solid and consistent reason for what I have termed ghost peaks. The problem is that - in this very example - the averaging changes the envelope and therefore gives a false impression of the waveform. 

If you have three peaks next to each other with the same amplitude, but one of them has a high bandwidth (=> the average of this peak and its neighbors is high) and the other two have a low bandwidth (=> the average of one such peak and its neighbors is lowe), the one with the high bandwidth may appear with many times the amplitude, which is quite misleading.

But solving this would probably consume to much time for an issue of this priority.

**Comment by raphywink** [comment]
Yep I agree! We could probably be a bit smarter about drawing the envelope but I have already tried several other options and none of them look as good as simply connecting the averages (think of zoomed in variants where you have 2 samples per pixel -> the average is a very good approximation).
