### ISSUE TITLE
suggestions for modals

### ISSUE THREAD

**Issue by MJochim** [IPS-LMU/EMU-webApp#203]
I have a few suggestions for the behavior of modals/of the modal service.

# Pressing enter in text fields

Especially in the login window, it is unnerving that pressing enter doesn't submit the form. I have implemented this in the branch `loginReturn`. The tests for LoginCtrl still fail; otherwise this could be merged into master.

This could be implemented for other modals as well, which would require that they handle setEditing() properly (see below) plus one of these:

- a way for the handlekeystrokes directive or the modal service to call a default submit function in the modal's controller
- or that the code that opens the modal (vial modalService.open()) execute the submit function once the modal is resolved.

# Do not call setEditing(true)

Most modal controllers call viewState.setEditing(true) when one of their text fields is focussed. This seems erroneous because viewState.isEditing() indicates whether something in the annotation is being edited. It also causes a bug when pressing enter while such a text field is focussed:

Cannot read property 'substr' of null at Object.LevelService.sServObj.getlastID ([LevelService.js:329](https://github.com/IPS-LMU/EMU-webApp/blob/896354932989a0e89cd191215c03e492de52a6cc/app/scripts/services/LevelService.js#L329))

# Hierarchy-related stuff upon closing

modalService.close() does shut down the hierarchy modal properly (see [here](https://github.com/IPS-LMU/EMU-webApp/blob/397eedf2a0fb98647ebce8846fc78e45868c6cc7/app/scripts/services/modalService.js#L83)).

I think we should also do this in all the other functions that can close a modal (closeAndResolve, confirm, select, confirmContent)?

# Re-init modalService when a modal is opened

The private variables (sServObj) in modalService (e.g. dataIn, dataOut, force) are only initialised when the modal service is instantiated, but not when a new modal is opened.

Example: If a force modal is opened first and then a non-force modal, force is not set to false.

**Comment by raphywink** [comment]
Pressing enter in text fields: yes I fully agree! It would be nice to also have a visual indication what button is pressed (by some form of highlighting of the respective button) when enter is pressed. 

Do not call setEditing(true): setEditing is probably a bad name for it (probably something we kept and dragged along from an old version). Maybe a refactor to something like `inTextField` would be more appropriate?

Hierarchy-related stuff upon closing: don't quite get what you mean by this? Don't they call the same function? [here](https://github.com/IPS-LMU/EMU-webApp/blob/397eedf2a0fb98647ebce8846fc78e45868c6cc7/app/views/showHierarchyModal.html#L31) vs. [here](https://github.com/IPS-LMU/EMU-webApp/blob/397eedf2a0fb98647ebce8846fc78e45868c6cc7/app/views/help.html#L22) when closed?

Re-init modalService when a modal is opened: will look into it (not now though :-)) thanks for the hint! Will have to maybe check on taredown of modal and if force was set then to reset it to it's default values.

**Comment by MJochim** [comment]
Just noted again that the re-init thing is a real problem. I am working on the anagest feature and #236 and my current problem is:

The handlekeystrokes directive kind of force-closes a modal when the user hits enter. If the modal has not defined its dataOut by then, it actually resolves to the dataOut of the previous modal.

E.g., I connect to ws://localhost and then try to insert a gesture. I get a modal that asks me to choose between two contours. It is now possible that it resolves not to one of the two contours, but rather to ws://localhost - wtf.

**Comment by MJochim** [comment]
With 72d289e, I implemented the last point (re-init modalService). @raphywink I hope there is no modal (or combination of two modals) that relies on the buggy behavior. But I cannot think of one that would.

**Comment by raphywink** [comment]
I can't either. The only mechanic that uses 2 modals is anagest mechanic.

**Comment by raphywink** [comment]
will switch to non-custom modals after angular 2+ upgrade
