### ISSUE TITLE
improve json schema validation using djv

### ISSUE THREAD

**Issue by julianpoemp** [IPS-LMU/EMU-webApp#216]
I found another json schema validation library, which should have a better performance than the jsonschema package: 
djv: [https://github.com/korzio/djv#readme](url)

Statistics:
[https://github.com/ebdrup/json-schema-benchmark](url)

If you compare the results, jsonschema has an error rate of ~ 6% while djv has an error rate of ~  0,09%. djv seems to be much faster, too. Perhaps this could improve the start performance of your Emu-WebApp.

I will try it out in the OCTRA repository to validate schema files.

**Comment by raphywink** [comment]
I have never really noticed a bottleneck in our application using jsonschema as we only have a tiny amount of files to validate on bundle load. Did you have an issue with performance in OCTRA?

**Comment by julianpoemp** [comment]
I was looking for a way to parse JSON using schema files and found this statistics and that you are using jsonschema. With this post I just wanted to show, that there are other solutions than jsonschema that have (seemingly) better performance stats. If you don't have any performance issues, it's all right :)
