### ISSUE TITLE
Disable sidebar controls for non-loaded bundles

### ISSUE THREAD

**Issue by MJochim** [IPS-LMU/EMU-webApp#218]
The bundle list sidebar contains up to three controls for every bundle (save button; finished editing; comment). They are all active for all bundles, although only one bundle can be loaded at a time. This does not really make sense and it can be quite confusing, particularly in cases like this:

- Load a bundle
- Make some change but do not save
- Tick "finished editing" for a different bundle
- The app will ask you whether you want to save your changes: click cancel
- As a result, the tick of the second bundle is visually modified but this will never be saved to the server

I suggest to hide the save button and disable the other controls for all bundles but the loaded one. Seems easy and natural. Hiding the save button would, as a side effect, free some space for long bundle names.

**Comment by raphywink** [comment]
Implemented this. However we should keep an eye on what users say about the non-overflow feature of the comment (could lead to huge blocks in side bar when comments get really really really long)
