### ISSUE TITLE
Bundlelist: long bundle names cause overlay of scroll bar in Firefox

### ISSUE THREAD

**Issue by florianschiel** [IPS-LMU/EMU-webApp#225]
If you open the ema demo DB in Firefox, the names of the two bundles are too long to be displayed in the bundle list. Consequently, a scroll bar opens below each name, but the scroll bar partly overlaps the text which looks weird.
In Chrome (smaller font?) this does not happen, but probably will happen in bundles with long names?
![emu-webapp](https://user-images.githubusercontent.com/3428731/27865795-3e56703a-6194-11e7-9007-0ac43fb1b62b.png)

**Comment by raphywink** [comment]
Thanks for this! As Macs have disappearing scrollbars in Chrome and Firefox I never noticed... will probably have to implement a custom scrollbar that works on every platform...
