### ISSUE TITLE
Crash on zooming through large files

### ISSUE THREAD

**Issue by MJochim** [IPS-LMU/EMU-webApp#227]
Having loaded the same large file as in #226, I discovered a condition where the web app crashes (almost always but not always on my machine; using Chromium 59).

**Steps to reproduce**

1. Load the file
2. Zoom in once
3. Zoom out twice very quickly

I am not sure if this is just a problem with Chromium's memory limit, but the app never seems to crash when I do step 3 slowly.

**Comment by raphywink** [comment]
same as #226
