### ISSUE TITLE
Video support?

### ISSUE THREAD

**Issue by psibre** [IPS-LMU/EMU-webApp#243]
Quick question, asked here because I'm not sure where else to:

Is there any capability, current or planned, to support multimedia data, specifically videos?

**Comment by raphywink** [comment]
Unfortunately I don't really have an answer to that question :-). We have been contemplating adding video support as part of the 2D canvases. However, that would be quite a lot of work as we would have to support server side streaming, as video files would quickly become to large to request as a single chunk from the server (and we would have to implement it in R so our serve() function supports it). So maybe in the distant future depending on what our resources permit... 

Sorry for the vague answer...

**Comment by psibre** [comment]
@raphywink Thanks for the fast response and insight! So it sounds like something that would take significant additional development at this point...

**Comment by raphywink** [comment]
Yep. Will try to do a bit of exploring of what we could do though... maybe it isn't as much work as I am imagining it to be. Will keep you posted...

**Comment by MJochim** [comment]
Starting next year in March, we have some funding to implement video annotation. It will most likely be based on IPS-LMU/Octra. But while we're at it, I hope we can contribute our efforts to EMU-webApp as well.
