### ISSUE TITLE
Keyboard shortcut shortcut?

### ISSUE THREAD

**Issue by FredrikKarlssonSpeech** [IPS-LMU/EMU-webApp#247]
Learning the shortcuts are key for starting to use the system. However, in the web-app you need to (as far as I understand this) press the emu bird and then select the keyboard shortcuts section.

I am sure that knowing exactly which version of the web app I am working on is important information, but I am also sure that users may not want to recheck that information 15-30 times per transcription session when they are learning the system, but they might want to check keyboard shortcuts with that frequency.

I have not been able to print the manual page with any reasonable quality and layout retained.

So, I suggest that there should be either a shortcut in the web app that leads directly to the keyboard shortcuts page, or a separate cheatsheet or something similar for download.

**Comment by MJochim** [comment]
Please ignore the "MJochim added a commit that referenced this issue" ... Used the wrong number accidentally ;-).

As to the issue: I completely agree with you. When you are new to the app, it should be possible to get to the list of shortcuts faster. Note that @raphywink is working on an improved manual; the new version might replace the Emu bird entirely. But this obviously takes a lot of time and I cannot promise anything about the when and the how exactly. I do, however, appreciate the idea to include a printable keyboard cheat sheet.

As a quick workaround: For me it seems to work (currently using Chromium 62) to highlight the table of keyboard shortcuts, and then choose "selection only" in the print dialog. Not a perfectly laid-out cheat sheet, but reasonable to work with: [EMU-webApp-Shortcuts.pdf](https://github.com/IPS-LMU/EMU-webApp/files/1568583/EMU-webApp-Shortcuts.pdf)

**Comment by raphywink** [comment]
I would like to move all the keyboard shortcuts into the manual so we don't have several places containing the same information. The Emu bird will then either just href there or integrate that section using an iframe-esque approach.
