### ISSUE TITLE
Correction tool?

### ISSUE THREAD

**Issue by FredrikKarlssonSpeech** [IPS-LMU/EMU-webApp#248]
It seems that the correction tool is not working, and as far as I can see only mentioned in the documentation when keyboard bindings are described. Pressing 4 on a formant display pane does not give me an ability to edit tracks though.

It may be of course that this is a browser issue. I am using Chrome  63.0.3239.132

**Comment by raphywink** [comment]
I am on Chrome version 63.0.3239.132 and it seems to be working just fine. Could you test it with the ae demo db in the EMU-webApp? Navigate to http://ips-lmu.github.io/EMU-webApp/, under the open demo button in the top menu bar click on ae then press 1 or 2 to correct the first or second formant.

Is your database configured to overlay the formants (frequency aligned) onto the spectrogram? This has to be the case to correct formants...

**Comment by FredrikKarlssonSpeech** [comment]
Yes, that works, and you are right in thinking that what did not work was signals that was not formant tracks overlayed on a spectrogram. Overlayed formant tracks work fine, it seems. 

Other tracks should not be editable then? I must have missed this information in the docs somewhere I think.

**Comment by raphywink** [comment]
Currently only a spectrogram overlayed track called FORMANTS can be edited. That might change in future releases though. I am not really that happy about the special implicit meaning of the FORMANTS track. In future we should consider making that an explicit configuration option like e.g. `"editable": true/false` and `"freqAlign": true/false`
