### ISSUE TITLE
multichannel signal transcription (question)

### ISSUE THREAD

**Issue by ghost** [IPS-LMU/EMU-webApp#252]
Hello sirs tks for this wonderful app.

My job is to transcribe a wav with three channels (audio + oral airflow + nasal flow). I shall use these three information to make a good transcription.

Is it possible to do in EMU ? I don't find it in documentation. In praat I just merge these three signal into a stereo wav and it's good to go.

Tks !

**Comment by raphywink** [comment]
Glad you like it :-)

Under `OSCI/SPEC settings` you can select the current channel. Currently it is however only possible to view one channel at a time.
