### ISSUE TITLE
Formant correction not working when using numFormants  > 4 (default)

### ISSUE THREAD

**Issue by ecanoc** [IPS-LMU/EMU-webApp#264]
Hi, I configured EMU-webApp to do formant correction on my own dataset (Chrome Version 75.0.3770.80 (64-bit)). However, I  changed the default parameters in forest (wrassp) to extract 5 formants instead of the default =4. The formants are extracted and correctly displayed (overlaid onto the spectrogram). However, I can only manually correct formants 1 to 4. The keyboard shortcuts( 1 = first formant, 2 = second formant, …) do not seem to activate higher formants for correction. Is this the case or am I missing something?
Thanks

**Comment by raphywink** [comment]
Yep, currently only contours 1-4 can be selected. As it should be super simple to do implement I'll see if I can squeeze it into the next release (currently focusing on the EMU-webApp2, which will probably have a slightly different approach to correcting contours)

**Comment by raphywink** [comment]
Yep, currently only contours 1-4 can be selected. As it should be super simple to implement I'll see if I can squeeze it into the next release (currently focusing on the EMU-webApp2, which will probably have a slightly different approach to correcting contours)

**Comment by ecanoc** [comment]
Great, do let me know if you get to it. Thanks.

**Comment by raphywink** [comment]
Will do! I'll leave the issue open until it is implemented...
