### ISSUE TITLE
snap to zero crossing does not work on EVENT levels

### ISSUE THREAD

**Issue by kirbyj** [IPS-LMU/EMU-webApp#265]
You can x all day long, but nothing happens...

**Comment by raphywink** [comment]
Seems to work fine with me:
![snap2zero_1](https://user-images.githubusercontent.com/435436/69959146-b80bf580-1506-11ea-8218-5725a9bdeed8.png)

then pre-selecting a bounday and hitting x moves it to the next zero crossing point:

![snap2zero_2](https://user-images.githubusercontent.com/435436/69959190-d3770080-1506-11ea-963d-5058fd547cfa.png)

**Comment by kirbyj** [comment]
Upon further investigation: something seems to be happening, but the display is not updated?

DIagnosis is that when hitting **z**, there is indication that something was undone, but the location of the boundary on the screen is not updated. 

Step 1: initial state:
![1](https://user-images.githubusercontent.com/7825539/69961825-48662c80-153f-11ea-88b1-16cfdb4cd62c.png)

Step 2: move the Event to a non-zero location:
![2](https://user-images.githubusercontent.com/7825539/69961827-48fec300-153f-11ea-8853-bd144fba92f7.png)

Step 3: hit **x** (nothing changes):
![3](https://user-images.githubusercontent.com/7825539/69961829-48fec300-153f-11ea-8069-0931cc43ee51.png)

Step 4: hit **z** first time (nothing changes, but note type of undo event):
![4](https://user-images.githubusercontent.com/7825539/69961830-49975980-153f-11ea-863e-83c712ddf902.png)

Step 5: hit **z** second time (Event moves back to original location)
![5](https://user-images.githubusercontent.com/7825539/69961831-49975980-153f-11ea-89ba-c3c61599b598.png)

**Comment by raphywink** [comment]
Damn... was able to reproduce the issue. Was testing with segment boundaries and there everything seems to work fine. There is def. something busted with events... will have to investigate!

**Comment by kirbyj** [comment]
Yeah, segment boundaries work fine; it's just events. Cheers!

**Comment by raphywink** [comment]
Will be in next release. Will try to get that out asap.
