### ISSUE TITLE
Bundle list filtering in left sidebar could be more user-friendly

### ISSUE THREAD

**Issue by muneson** [IPS-LMU/EMU-webApp#266]
The EMU-webApp displays the bundle list in the left sidebar, grouped by session. 

If I filter the bundles, I expect to see either a list of the matching bundles;
or possibly a list of all sessions which contain at least one matching bundle 
(and on clicking the session, it opens and reveals those). 

As it currently works, however, I still get a list of all sessions of the corpus, only
that the ones not having any matching bundles turn out to be empty if you click
them (and you do have to click them to find out).  This is not very helpful for corpora 
over a certain size. For instance, I am at the moment working with a multilingual 
(50+ languages) corpus of  250 sessions * 4 bundles. The most common filtering 
I want to do is on the iso language code, which is part of both session and bundle 
name; but even on this relatively small corpus that easily gets tiring. 

My apologies if this is configurable behaviour; but even if it is, I think the default could
be more user-friendly. Here is a couple of ways (not mutually exclusive) 
I can think of to improve the user  experience; surely, there are others.

a) The filtering works on bundles as before, but sessions with no matching bundles
are hidden. This I think should be done in all cases.

b) The user gets to choose if to filter on session names, bundle names, or  
(adding another search field) both

c) The user gets to choose what to do with found results -- show them in a list of 
matching bundles (possibly useful if you have many sessions with few bundles in each)
or in a list of sessions (possibly useful if you  have many bundles but grouped into few sessions),
or in a list of bundles grouped by session.

**Comment by raphywink** [comment]
I agree that this would be desirable behaviour. However, I think I'd rather try to get this working in the EMU-webApp2 (https://github.com/IPS-LMU/EMU-webApp2). I'll open up a feature request there and link this issue in it (and also close this issue then).
