### ISSUE TITLE
add comments and have them saved?

### ISSUE THREAD

**Issue by kirbyj** [IPS-LMU/EMU-webApp#268]
Assume you have created demo database `ae`.

1. edit the .json file to add `"bundleComments": true`, etc. to end of file:

```
"activeButtons": {
      "saveBundle": true,
      "showHierarchy": true
    },
"restrictions": {
      "showPerspectivesSidebar": true,
      "bundleComments": true,
      "bundleFinishedEditing": true
   }
```

2. Serve db, add comments on web-App and save everything.

3. Re-load and serve db:

```
db_handle = load_emuDB(dbPath, verbose = F)
serve(db_handle)
```
4. Check web-App and individual .json files for commented tokens, but comments have not been saved.

**Comment by raphywink** [comment]
Comments and finished editing values are stored in a users bundle list and not the annot.json file. I updated the `serve()` function to work with these a few weeks ago (might still not be in the CRAN release though... would have to double check):
```r
# list all files in session "0000"
bndls = list_bundles(db, 
                     session = "0000")
# write these to a bundle list called raphael.winkelmann
# therefore assigning them to that user (a dir bundleLists is created in the emuDB if not present)
write_bundleList(db, 
                 name = "raphael.winkelmann", 
                 bndls)

# serve db and list name of bundle.list
# and add a comment + save
serve(db, bundleListName = "raphael.winkelmann")

# test if comment is available
read_bundleList(db, 
                name = "raphael.winkelmann")
```

**Comment by raphywink** [comment]
Just checked and def. not in CRAN release yet so you'll need to install emuR via `devtools::install_github(IPS-LMU/emuR)`

**Comment by raphywink** [comment]
I should probably implement a check if `bundleComments` and/or `bundleFinishedEditing` is set to true and no bunldeListName is specified and issue a warning that these values will not be saved.

**Comment by brisaann** [comment]
Is there a way to set up the bundle list so that one bundle list name contains multiple sessions (where each session = a speaker with their individual set of tokens)?  I would like to serve all my sessions at once in the WebApp and collectively add/edit comments.  Right now I am creating one bundle list per individual session and serving each bundle list individually.

**Comment by raphywink** [comment]
https://github.com/IPS-LMU/emuR/commit/1b3c2d60f606398ff7ca522683a3cde50e483768 implements a warning (is actually an emuR issue not a EMU-webApp issue)

**Comment by raphywink** [comment]
@brisaann if you simply don't specify a session in `list_bundles()` then you'll get every bundle of the emuDB. Using the above code will then gen. a bundleList that contains every bundle of the emuDB.
