### ISSUE TITLE
Does not start inside RStudio anymore

### ISSUE THREAD

**Issue by klausj** [IPS-LMU/EMU-webApp#270]
The version 1.2.0 release on http://ips-lmu.github.io/EMU-webApp/ does not automatically  start inside RStudio anymore and displays strange (inverse?) colors which looks like a dark-theme.

OS: Ubuntu 18.04
R version 3.6.3 (2020-02-29) -- "Holding the Windsock"
Google Chrome 80.0.3987.122

`
> packageVersion('emuR')
[1] ‘2.0.4’

> serve(d)
Navigate your browser to the EMU-webApp URL: https://ips-lmu.github.io/EMU-webApp/ (should happen automatically)
Server connection URL: ws://localhost:17890
To stop the server either press the 'clear' button in the EMU-webApp, close/reload the webApp in your browser,
or call the httpuv::stopAllServers() function
cloning into '/tmp/RtmpLKfcts/EMU-webApp'...
Receiving objects:   1% (360/35902),   80 kb
Receiving objects:  11% (3950/35902),  712 kb
Receiving objects:  21% (7540/35902), 17028 kb
Receiving objects:  31% (11130/35902), 24131 kb
Receiving objects:  41% (14720/35902), 24691 kb
Receiving objects:  51% (18311/35902), 25379 kb
Receiving objects:  61% (21901/35902), 25795 kb
Receiving objects:  71% (25491/35902), 30323 kb
Receiving objects:  81% (29081/35902), 31587 kb
Receiving objects:  91% (32671/35902), 31995 kb
Receiving objects: 100% (35902/35902), 35314 kb, done.

> httpuv::stopAllServers()
Warnmeldung:
In file(con, "rb") :
  kann Datei '/tmp/RtmpLKfcts/EMU-webApp//EMU-webApp/dist/bundle.js' nicht öffnen: Datei oder Verzeichnis nicht gefunden
> 

`

**Comment by klausj** [comment]
Version 1.2.0 is not listed as release on GitHub. Was the version released by mistake?

**Comment by raphywink** [comment]
No not by mistake just 4got to tag it on GitHub on Friday. Am looking into the issue now...

**Comment by raphywink** [comment]
Should be fixed now! See: 1334d67a8132daae266bd would you mind testing it and closing the issue? I am aware of the missing version number on the welcome dialog btw. will look into that today

**Comment by klausj** [comment]
It is fixed! Thank you.
Is the dark-theme now default?

**Comment by raphywink** [comment]
Awesome! Thanks! Yes the dark theme is now the default...
