### ISSUE TITLE
disabling dark mode?

### ISSUE THREAD

**Issue by kirbyj** [IPS-LMU/EMU-webApp#271]
How does it work?

**Comment by raphywink** [comment]
Dark mode is the new default. Implementing switchable color modes is currently too much work. You can however switch the Spectrogram back to black-on-white either in the OSCI/SPEC settings or using the DBconfig

**Comment by raphywink** [comment]
4got to add how to configure it: https://github.com/IPS-LMU/EMU-webApp/blob/master/app/testData/newFormat/ae/ae_DBconfig.json#L203
