### ISSUE TITLE
Bundle loading stuck at "Parsing WAV file..."

### ISSUE THREAD

**Issue by samgregory** [IPS-LMU/EMU-webApp#275]
I've noticed an issue with using the online build of the EMU-webApp at http://ips-lmu.github.io/EMU-webApp/ where bundles get stuck during the "Parsing WAV file..." phase. 
This issue appears on the Safari browser on multiple devices and is easily replicated by opening a demo database. The issue does not occur when I open the page in a different browser.

<img width="2157" alt="Safarierrors" src="https://user-images.githubusercontent.com/4771552/77484748-6d303800-6e7f-11ea-9678-d12594769e40.png">

**Comment by raphywink** [comment]
Thanks for reporting this. Unfortunately being stuck at home atm I don't have a mac I can test this on (at work I have a MacBook, here I only have a Linux/Windows10 dual-boot machine). The only solution I have atm is switching to a different browser. We always recommend Chrome as it is what we use to develop the EMU-webApp in (i.e. by far the best tested browser).

**Comment by samgregory** [comment]
I found the exact commit that the bug first appeared - https://github.com/IPS-LMU/EMU-webApp/commit/c4ccbc4525a600fa0759855fdaa4321d6e9e8221

I will do some digging into the source code to see if I can isolate what is going on.

**Comment by samgregory** [comment]
Actually I think I have identified two issues:
1. That Safari can't open bundles the demo databases but other browsers can; there used to be an error message about but it seems to have disappeared.
2. That all browsers are now unable to open GITLAB databases because of an error in httpGetPath of IoHandlerService where the fetch command fails and thus the function returns an undefined response to the DBObjLoadSaveService https://github.com/IPS-LMU/EMU-webApp/blob/master/app/scripts/services/io-handler.service.ts#L70 - I have replicated this problem on builds since 7 Mar on Mac and PC (Safari and Edge) when trying to access GITLAB.

**Comment by samgregory** [comment]
I've confirmed the issue exists on Chrome as well.

I've found the offending code and made a pull request with the fixes for you #277

**Comment by raphywink** [comment]
Sorry I am a bit confused: 
regarding 1.) I now have access to Safari again and was able to reproduce the demo DB loading issue so I'll check it out
regarding 2.) see comment on pull request

> I've confirmed the issue exists on Chrome as well.

the GITLAB loading or the loading of the demo DBs? I've just tested loading the demo DBs on Chrome and Firefox and it works on Linux, Max and Windows 10

**Comment by raphywink** [comment]
Both issues should now be fixed.
