### ISSUE TITLE
Playback Keyboard Shortcuts don't execute on first attempt

### ISSUE THREAD

**Issue by brisaann** [IPS-LMU/EMU-webApp#276]
Please find, the Playback Keyboard Shortcuts (listed 1-4 below) do not execute on first attempt-- they require two attempts before working.  

1. 'f' (play entire file)
2. 'c' (play selected)
3. SPACE (play/pause in view)
4. SHIFT+SPACE (play/pause in view to end of file)

Other Keyboard Shortcuts seem to be working fine (i.e. Main Navigation Shortcuts: 'a', 'd', 'w', 's', and Labeling Shortcuts: 'z', SHIFT + z, enter, BACKSPACE, 'x').

**Comment by raphywink** [comment]
Thanks, for reporting this. A different user reported the same issue via email two/three days ago. I have already fixed the issue and it will be in the next release (maybe today but can't promise anything)
