### ISSUE TITLE
Issues with Save & exit

### ISSUE THREAD

**Issue by FredrikKarlssonSpeech** [IPS-LMU/EMU-webApp#279]
The web app now on https://ips-lmu.github.io/EMU-webApp/ freezes and stops working in the proper way when pressing "clear". It also seems that data is not saved (but I am not sure about that).

I placed a video of capturing the issue here:

https://www.dropbox.com/s/hrve15bw32rvlj9/emu_error.mov?dl=0

**Comment by raphywink** [comment]
Will be in next release. Thank for pointing it out!

**Comment by FredrikKarlssonSpeech** [comment]
No, sorry. The only reason was my hurry - and having both repositories up at the same time. 
Sorry about that.
