### ISSUE TITLE
Levels appear for certain files but not others

### ISSUE THREAD

**Issue by prudenceschneider** [IPS-LMU/EMU-webApp#286]
I have my "TARGET" tier showing up for some files in my database but not others:

add_levelDefinition(emuDBhandle = AKTOM,
                    name = "TARGET",
                    type = "EVENT")
list_levelDefinitions(AKTOM)
set_levelCanvasesOrder(AKTOM, perspectiveName = "default", 
                       order = c("ORT-MAU", "KAN-MAU", "MAU", "TARGET"))
fb.params= formals(wrassp::forest)

Here are two different files from the AKTOM database. The first has the target level included (and annotated with T, T1, and T2):
![image](https://user-images.githubusercontent.com/73071979/96373478-3cbc3c80-11c9-11eb-951f-5ad64774b6cd.png)

In the second, the TARGET level (which should be fourth from the top) isn't showing up:
![image](https://user-images.githubusercontent.com/73071979/96373465-28783f80-11c9-11eb-9512-bea48ea5f9fd.png)

This issue is replicated across multiple databases with no apparent pattern. The files correspond to interviews of 33 passages, and the TARGET level is missing for passages 12-33 in one interview, passages 27-33 in a second interview, passages 29-33 in a third interview, and for all 33 passages for a fourth interview.

**Comment by raphywink** [comment]
Ok that is strange! I just tried the following:

```{r}
create_emuRdemoData("~")
ae = load_emuDB("~/emuR_demoData/ae_emuDB/")

add_levelDefinition(emuDBhandle = ae,
                    name = "TARGET",
                    type = "EVENT")
list_levelDefinitions(ae)
set_levelCanvasesOrder(ae, perspectiveName = "default",
                       order = c("Phonetic", "Tone", "TARGET"))

serve(ae)
```
and that then shows the TARGET level for all of the bundles in the emuDB. Can you maybe check the _annot.json files in a text editor to see if they contain the TARGET level (on bundles where the EMU-webApp doesn't show the level)

**Comment by raphywink** [comment]
please reopen if this is still an issue
