### ISSUE TITLE
Hierarchy view create links not working

### ISSUE THREAD

**Issue by samgregory** [IPS-LMU/EMU-webApp#299]
Good morning,
Just noticed that on the latest build (1.3.7) it isn't possible to create links in the hierarchy view by holding down the shift key.
Thanks

https://github.com/IPS-LMU/EMU-webApp/blob/e953533694d76e51a90d8449cca85349c848fdf4/src/app/services/handleglobalkeystrokes.service.ts#L254

**Comment by raphywink** [comment]
yep thanks 4 this. Unfortunatelly the code you are pointing towards isn't the underlying issue. Will have a look at this asap (hopefully tomorrow)

**Comment by samgregory** [comment]
Thanks

**Comment by MJochim** [comment]
Our colleagues in Vienna just reported the same problem.
