### ISSUE TITLE
"Alignment" of audio playback and playback cursor 

### ISSUE THREAD

**Issue by MJochim** [IPS-LMU/EMU-webApp#33]
The playback cursor is somewhat faster than the actual playback.

**Tested on:**
ArchLinux (Chrome and Chromium)

**Steps to reproduce:**
Try selecting the beginning of a word (e.g. 'friends' in ae->msajc003) and then playing the entire file. You'll notice that the playback cursor has gone past the /r/ by the time you hear /f/.

**Comment by MJochim** [comment]
no longer reproducible; closing

**Comment by raphywink** [comment]
That's what I like to see... bugs that fix themselves :-)
