### ISSUE TITLE
Formant correction

### ISSUE THREAD

**Issue by raphywink** [IPS-LMU/EMU-webApp#82]
According to a student assistant the Formant correction does not work any more after you have a single file open for quite some time (30-60 mins) and you then load the next bundle. In her case the files are also rather large (45-60 seconds)

**Comment by georgraess** [comment]
do you know what exactly he/she meant with "does not work any more" ?
complete browser crash? browser hanging/not responding? formant not selectable via keys 1 2 3 etc ? formant selected but dots not moving up/down ?

**Comment by raphywink** [comment]
Closing due to lack of bug information. Will reopen if it appears again.
