### ISSUE TITLE
audio playback: only every second click/key hit works

### ISSUE THREAD

**Issue by florianschiel** [IPS-LMU/EMU-webApp#83]
Using Chromium under Ubuntu (where the heck can you see the version of Chromium?) I observed the following effect: all play buttons or keys that cause audio playback work only every second click/hit.
Other events work every time.
Since this is only on my laptop, not on my workstation, it is probably a rare bug caused by my hardware? Nevertheless I'd like to find out why this is.

**Comment by raphywink** [comment]
☰ -> about chromium should give you the version number. You don't by any chance mean the intended behavior that the playback is stopped before it can be replayed: "state=playing audio -> if any button/key is pushed to play audio (e.g. play selection) it will stop the current playback (and won't automatically restart playback)"

**Comment by raphywink** [comment]
Problem only seems to occur on Florians Laptop. Closing issue for now...
