### ISSUE TITLE
No font scaling on SSFF tracks

### ISSUE THREAD

**Issue by raphywink** [IPS-LMU/EMU-webApp#92]
Font scaling on window resize does not work for the message `Zoom in to see countour(s)` on SSFF tracks.

**Comment by georgraess** [comment]
most of the scaling stuff is done inside the ssffTrack directive using the Drawhelperservice while the text "Zoom in to see.." is being generated inside the drawssff directive (where the values are drawn, if there are any)
should we move the "zoom in" i.e. the else block (lines 214-230 in drawssff.js) into ssffTrack also ? which already watches viewState.timelineSize or should we leave it there ? 'cause all the markup stuff is also there ?

or do you think it belongs to the actual values and it should stay where it is ?
(but then we also have to watch viewState.timelineSize inside drawssff, which is currently not the case)
