### ISSUE TITLE
watchers called on initialization

### ISSUE THREAD

**Issue by MJochim** [IPS-LMU/EMU-webApp#93]
@georgraess: You added a check
`if(newValue !== undefined)`
to all the watches in my directives/emuhierarchy.js. I guess you did it so they do not act when the variable is initialized. Now I need one of them to act if its value changes from something else to undefined (note that you didn't edit that one because it's not yet in master branch).

According to [1] we can avoid watches being active on initialization by checking if newVal and oldVal are the same. Can I do that, overwriting your changes?

[1] https://docs.angularjs.org/api/ng/type/$rootScope.Scope#$watch

**Comment by georgraess** [comment]
yeah, of course you can
